# Generated by Django 4.0.6 on 2022-07-09 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reccomendai', '0002_alter_product_name_alter_shop_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chequeproduct',
            name='shop_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reccomendai.shopproduct'),
        ),
    ]
